### ISSUE TITLE
Add option to supply initial value function

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/ContinuousDPs.jl#11]

**Comment by tokupooh** [comment]
In this package, `v` and `Tv` are objects that only contain values. 

To use initial guess, we may need to add option to supply basis coefficients like `C` in `solve`,`operator_iteration!`,`bellman_operator!`,`policy_iteration_operator!`.

Do you have any suggestion?

**Comment by oyamad** [comment]
Add an option `v_init`, a `Vector` of values, from which the initial `C` can be computed.
